spring.application.name=gateway-service-api
server.port=9090

#Eureka server url
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/

#Keycloak configuration
spring.security.oauth2.resourceserver.jwt.token-uri=http://localhost:8080/realms/cpd/protocol/openid-connect/token
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/cpd
public.key.string=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2o8ktShYo0TbX9RK03o1qhDYZDJ1P7/8aXEaeiolYZvMn3y5bzH00VySOHm0bjUIx7fD1K+4IfxetbfOW5MSu7Ehi/VpF+l30PZZvMDUKs1itVzQj1YTATdPYgQ68DXp5BhfxliAVmzriIS91HEfORLeobMkMcigoo6hURwZRdp4mD4M/4QliLfFgDch3tvmEtcJp/JSF4S6L5DfPfAx0nXQX0moZMtBKxyB+BydjeGYSA+fp7gQrQLpGvIAe8d2wvtzip9CdsQ3doJWmJxThLwySaE2MX4lnickJ+42LfMXjx+6cnMc1SZh2pKWYxeFnuHaEfvZRM5LqlWyhnRsAQIDAQAB

keycloak.config.realm=cpd
keycloak.config.server-url=http://localhost:8080/
keycloak.config.client-id=cpd-client
keycloak.config.grant-type=password
keycloak.config.name=hamdhiharis@gmail.com
keycloak.config.secret=8VvfeSUaqBm824JUPlqGcQjPNVqmhpA7G927JuhqmKG7QLcBGcLN18mtheV6UXdwvgsCPBWqlBFhHP1FHEdhWm
keycloak.config.password=1234